version: "3"

services: 
    django_app:
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./app-api:/app-api
        command: >
            sh -c  "python manage.py wait_for_db && 
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DB_HOST=postgres_db
            - DB_NAME=django_app
            - DB_USER=postgres
            - DB_PASSWORD=password123
        depends_on: 
            - postgres_db
    postgres_db:
        image: postgres:10-alpine
        environment: 
            - POSTGRES_DB=django_app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password123
        ports: 
            - 5435:5432