version: "3"

services: 
    django_app:
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./app-api:/app-api
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
 